# Generated by Django 4.0.5 on 2022-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.TextField(default=1, max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='d_date',
            field=models.DateField(auto_created=True, verbose_name='дата сдачи'),
        ),
    ]
